version: "3.9"

services:
  database_seu_estoque:
    image: postgres
    container_name: database_seu_estoque
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=seu_estoque
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: api_seu_estoque
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_seu_estoque
    depends_on:
      - database_seu_estoque
      
volumes:
  pgdata:
    driver: local
